#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

fulcrum_connrate - Plugin to monitor Fulcrum server.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/fulcrum.
Edit the FULCRUM_RPC setting to specify the location of FulcrumAdmin.

=head1 NOTES

Uses env.FULCRUM_RPC in /etc/munin/plugin-conf.d/fulcrum

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Fulcrum Connection Rate'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel connections per hour'
	echo 'graph_category Fulcrum'
	echo 'conn_rate.label connections'
	echo 'conn_rate.type DERIVE'
	echo 'conn_rate.min 0'
	echo 'conn_rate.max 1000000'
	echo 'conn_rate.cdef conn_rate,3600,*'
	exit 0
fi

sessions=`${FULCRUM_RPC} getinfo | grep \"clients_connected\" | grep -o '[0-9]*'`
echo "conn_rate.value " $sessions
