#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

fulcrum_ses - Plugin to monitor Fulcrum server.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/fulcrum.
Edit the FULCRUM_RPC setting to specify the location of FulcrumAdmin.

=head1 NOTES

Uses env.FULCRUM_RPC in /etc/munin/plugin-conf.d/fulcrum

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Fulcrum Caches'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel per second'
	echo 'graph_category Fulcrum'

        echo 'LRU_cache_block_height_to_txhashes_misses.label LRU cache block height to txhashes misses'
        echo 'LRU_cache_block_height_to_txhashes_misses.type DERIVE'
        echo 'LRU_cache_block_height_to_txhashes_misses.min 0'
        echo 'LRU_cache_block_height_to_txhashes_hits.label LRU cache block height to txhashes hits'
        echo 'LRU_cache_block_height_to_txhashes_hits.type DERIVE'
        echo 'LRU_cache_block_height_to_txhashes_hits.min 0'
#        echo 'LRU_cache_block_height_to_txhashes_nblocks.label LRU cache block height to txhashes nBlocks'
#        echo 'LRU_cache_block_height_to_txhashes_nblocks.type GAUGE'

        echo 'LRU_cache_txnum_to_txhash_misses.label LRU cache txnum to txhash misses'
        echo 'LRU_cache_txnum_to_txhash_misses.type DERIVE'
        echo 'LRU_cache_txnum_to_txhash_misses.min 0'
        echo 'LRU_cache_txnum_to_txhash_hits.label LRU cache txnum to txhash hits'
        echo 'LRU_cache_txnum_to_txhash_hits.type DERIVE'
        echo 'LRU_cache_txnum_to_txhash_hits.min 0'
#        echo 'LRU_cache_txnum_to_txhash_nitems.label LRU cache txnum to txhash nItems'
#        echo 'LRU_cache_txnum_to_txhash_nitems.type GAUGE'

        echo 'subs_cache_misses.label subscriptions cache misses'
        echo 'subs_cache_misses.type DERIVE'
        echo 'subs_cache_misses.min 0'
        echo 'subs_cache_hits.label subscriptions cache hits'
        echo 'subs_cache_hits.type DERIVE'
        echo 'subs_cache_hits.min 0'
#        echo 'subs_bucket_count.label subscriptions bucket count'
#        echo 'subs_bucket_count.type GAUGE'

	exit 0
fi

TFILE=/tmp/munin-fulcrum-reqcounts-$$
curl -s http://127.0.0.1:8081/stats > $TFILE

jq '.Storage.caches."LRU Cache: Block Height -> TxHashes"."~misses"' $TFILE | { read misses; echo "LRU_cache_block_height_to_txhashes_misses.value" $misses; }
jq '.Storage.caches."LRU Cache: Block Height -> TxHashes"."~hits"' $TFILE | { read hits; echo "LRU_cache_block_height_to_txhashes_hits.value" $hits; }
#jq '.Storage.caches."LRU Cache: Block Height -> TxHashes"."nBlocks"' $TFILE | { read nBlocks; echo "LRU_cache_block_height_to_txhashes_nblocks.value" $nBlocks; }
jq '.Storage.caches."LRU Cache: TxNum -> TxHash"."~misses"' $TFILE | { read misses; echo "LRU_cache_txnum_to_txhash_misses.value" $misses; }
jq '.Storage.caches."LRU Cache: TxNum -> TxHash"."~hits"' $TFILE | { read hits; echo "LRU_cache_txnum_to_txhash_hits.value" $hits; }
#jq '.Storage.caches."LRU Cache: TxNum -> TxHash"."nItems"' $TFILE | { read nItems; echo "LRU_cache_txnum_to_txhash_nitems.value" $nItems; }
jq '.SubsMgr."subscriptions cache misses"' $TFILE | { read misses; echo "subs_cache_misses.value" $misses; }
jq '.SubsMgr."subscriptions cache hits"' $TFILE | { read hits; echo "subs_cache_hits.value" $hits; }
#jq '.SubsMgr."subscriptions bucket count"' $TFILE | { read count; echo "subs_bucket_count.value" $count; }

rm $TFILE
