#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

fulcrum_peers - Plugin to monitor Fulcrum server.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/fulcrum.
Edit the FULCRUM_RPC setting to specify the location of fulcrum_rpc.py.

=head1 NOTES

Uses env.FULCRUM_RPC in /etc/munin/plugin-conf.d/fulcrum

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Fulcrum Peers'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel peers'
	echo 'graph_category Fulcrum'
	echo 'bad.label Bad'
	echo 'bad.type GAUGE'
	echo 'current.label Current'
	echo 'current.type GAUGE'
	echo 'failed.label Never'
	echo 'failed.type GAUGE'
#	echo 'stale.label Stale'
#	echo 'stale.type GAUGE'
	echo 'blacklisted.label Blacklisted'
	echo 'blacklisted.type GAUGE'
	echo 'good.label Good'
	echo 'good.type GAUGE'
	echo 'peers.label Total'
	echo 'peers.type GAUGE'
	exit 0
fi

#{
#    "closing": 0,
#    "daemon": "sampc8:8332/",
#    "daemon_height": 453777,
#    "db_height": 453777,
#    "errors": 0,
#    "groups": 1,
#    "logged": 0,
#    "paused": 0,
#    "peers": {
#        "bad": 11,
#        "good": 54,
#        "never": 11,
#        "stale": 0,
#        "total": 76
#    },
#    "pid": 62669,
#    "requests": 0,
#    "sessions": 47,
#    "subs": 5840,
#    "txs_sent": 1,
#    "uptime": "02m 58s"
#}

TFILE=/tmp/munin-fulcrum-peers-$$
${FULCRUM_RPC} peers > $TFILE

echo "bad.value `grep Bad $TFILE | wc -l`"
CURRENT=`grep Good $TFILE | wc -l`
echo "current.value $CURRENT"
echo "failed.value `grep Failed $TFILE | wc -l`"
#echo "stale.value `grep stale $TFILE | grep -o '[0-9]*'`"
echo "peers.value `cat $TFILE | wc -l`"

BLACKLISTED=`${FULCRUM_RPC} peers | grep Good | python3 -c '
import sys, json, requests
blacklist = json.loads(requests.get("https://electrum.org/blacklist.json").text)
for peer in sys.stdin:
        host = peer.split(" ",1)[0]
        if any(item in blacklist for item in (host, "*." + ".".join(host.split(".")[-2:]))):
                print(peer.rstrip())
' | wc -l`

echo "blacklisted.value $BLACKLISTED"
echo "good.value `expr $CURRENT - $BLACKLISTED`"

rm $TFILE
