#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

fulcrum_bw - Plugin to monitor Fulcrum server.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/fulcrum.
Edit the FULCRUM_RPC setting to specify the location of fulcrum_rpc.py.

=head1 NOTES

Uses env.FULCRUM_RPC in /etc/munin/plugin-conf.d/fulcrum
Uses the command "nethogs"

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Fulcrum Bandwidth'
	echo 'graph_args --base 1024 -l 0'
	echo 'graph_vlabel bytes per ${graph_period} recv (-) / sent (+)'
	echo 'graph_category Fulcrum'
	echo "bitcoindrecv.type GAUGE"
	echo "bitcoindrecv.label br"
	echo "bitcoindrecv.graph no"
	echo "bitcoindsent.type GAUGE"
	echo "bitcoindsent.label bc"
	echo "bitcoindsent.negative bitcoindrecv"
	echo "fulcrumrecv.type GAUGE"
	echo "fulcrumrecv.label exr"
	echo "fulcrumrecv.graph no"
	echo "fulcrumsent.type GAUGE"
	echo "fulcrumsent.label ex"
	echo "fulcrumsent.negative fulcrumrecv"
#	echo "torrecv.type GAUGE"
#	echo "torrecv.label torr"
#	echo "torrecv.graph no"
#	echo "torsent.type GAUGE"
#	echo "torsent.label tor"
#	echo "torsent.negative torrecv"
	exit 0
fi

TFILE=/tmp/munin-fulcrum-bw-$$
${FULCRUM_RPC} getinfo > $TFILE
pid=`grep pid $TFILE | grep -o '[0-9]*'`

/usr/sbin/nethogs -t -c 2 -d 10 > $TFILE 2> /dev/null

grep /${pid}/ $TFILE | awk '{print "fulcrumsent.value " $2*1024; print "fulcrumrecv.value " $3*1024}'
grep bitcoind $TFILE | awk '{print "bitcoindsent.value " $2*1024; print "bitcoindrecv.value " $3*1024}'
#grep tor $TFILE | awk '{print "torsent.value " $2*1024; print "torrecv.value " $3*1024}'



rm $TFILE


