#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

fulcrum_tx - Plugin to monitor Fulcrum server.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/fulcrum.
Edit the FULCRUM_RPC setting to specify the location of FulcrumAdmin.

=head1 NOTES

Uses env.FULCRUM_RPC in /etc/munin/plugin-conf.d/fulcrum

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Fulcrum Transactions'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel transactions per hour'
	echo 'graph_category Fulcrum'
	echo 'txs_sent.label txs_sent'
	echo 'txs_sent.type DERIVE'
	echo 'txs_sent.min 0'
	echo 'txs_sent.max 1000000'
	echo 'txs_sent.cdef txs_sent,3600,*'
	exit 0
fi

#{
#    "closing": 0,
#    "daemon_height": 443912,
#    "db_height": 443912,
#    "errors": 0,
#    "groups": 1,
#    "logged": 0,
#    "peers": 53,
#    "pid": 23142,
#    "requests": 0,
#    "sessions": 50,
#    "subs": 974,
#    "txs_sent": 1
#}

TFILE=/tmp/munin-fulcrum-tx-$$
curl -s http://127.0.0.1:8081/stats > $TFILE

jq '."Server Manager"."transactions sent"' $TFILE | { read txs; echo "txs_sent.value" $txs; }

rm $TFILE
